### ISSUE TITLE
pycox in a singularity container for HPC

### ISSUE THREAD

**Issue by paulamartingonzalez** [havakv/pycox#107]
Hi @havakv! I am trying to install pycox on a singularity container to run some codes in a HPC cluster.

I did the installation via pip (`pip install pycox`) but it crashes when importing it in the cluster with the following error:

```
Traceback (most recent call last):
File "test.py", line 19, in <module>
from pycox.models import LogisticHazard
File "/opt/conda/lib/python3.6/site-packages/pycox/__init__.py", line 9, in <module>
import pycox.datasets
File "/opt/conda/lib/python3.6/site-packages/pycox/datasets/__init__.py", line 1, in <module>
from pycox.datasets import from_deepsurv
File "/opt/conda/lib/python3.6/site-packages/pycox/datasets/from_deepsurv.py", line 5, in <module>
from pycox.datasets._dataset_loader import _DatasetLoader
File "/opt/conda/lib/python3.6/site-packages/pycox/datasets/_dataset_loader.py", line 12, in <module>
_PATH_DATA.mkdir(parents=True, exist_ok=True)
File "/opt/conda/lib/python3.6/pathlib.py", line 1248, in mkdir
self._accessor.mkdir(self, mode)
File "/opt/conda/lib/python3.6/pathlib.py", line 387, in wrapped
return strfunc(str(pathobj), *args)
OSError: [Errno 30] Read-only file system: '/opt/conda/lib/python3.6/site-packages/pycox/datasets/data'
```

The singularity image is by definition a read only system, is there any way to do a work around? Thanks in advance!

**Comment by havakv** [comment]
So, it look like it crashes because it is trying to create a folder in which is can store downloaded datasets. However, you don't have write access to `'/opt/conda/lib/python3.6/site-packages/pycox/datasets/data'`. One workaround would be to set the environment variable `PYCOX_DATA_DIR` to some directory where you can write, as described [here](https://github.com/havakv/pycox#datasets). I would suggest that you set this in your `~/.bashrc` file.

If this doesn't work, you can try to install from source as described [here](https://github.com/havakv/pycox#install-from-source), but use `pip install -e .` instead to make sure it is in the path where you cloned it.

Let me know how it goes

**Comment by paulamartingonzalez** [comment]
Dear @havakv thanks so much! The first solution works perfect and I was already able to run my codes in the HPC using the container 😃
