### ISSUE TITLE
How do I extend the prediction window for Cox-Time model?

### ISSUE THREAD

**Issue by cecil185** [havakv/pycox#24]
I would like to predict the survival probabilities further into the future than the model predicts.
I tried to set max_duration to 1200 when predicting the probabilities as such:
surv = model.predict_surv_df(x_test, max_duration=1200)

but printing the last 8 rows of surv shows that 1) it does not predict further than 1012 periods and 2) the periods are not increasing by the same amount in each row (993>998>999>1005)

print(surv.iloc[920:,:1])
989   0.469803
991   0.469803
992   0.469803
993   0.469803
998   0.469803
999   0.469803
1005  0.469803
1012  0.469803

How do I extend the prediction window and obtain a survival probability for every single period?

**Comment by havakv** [comment]
The Cox-methods' predictions are dependent on the `baseline_hazards_` which are computed non-parametrically from the training set (similarly to the Kaplan-Meier estimator). The methods can therefore only compute predictions at the time-points defined by the `baseline_hazards_`. 
So when you are only able to obtain predictions up to time 1012, this is likely because 1012 is the highest duration in your training set. The argument `max_duration` can only be used to decrease the maximum prediction duration (to decrease computations), and cannot be used to increase the maximum duration.

If you want to interpolate between the time-points of your predictions, or if you want to extrapolate beyond them, you need to code this on your own, as this is not supported. 
I would also advice you to be careful when prediction for higher durations than what you observe in your training set. As you have no data at such high times, your estimates will probably not be very good.
